version: '3'

services:
  node-cubicle:
    build: .
    image: brainpower/node-cubicle
    ports:
      - '8443:8443'
    volumes:
      - ".:/root/project/"
    entrypoint: ["code-server", "--allow-http", "--no-auth"]
